name: Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install_requrements
      run: pip install -r dev_requirements.txt
      
    - name: coverage
      run: coverage run -m pytest && coverage html
